# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_enrichment_tools', [dirname(__file__)])
        except ImportError:
            import _enrichment_tools
            return _enrichment_tools
        if fp is not None:
            try:
                _mod = imp.load_module('_enrichment_tools', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _enrichment_tools = swig_import_helper()
    del swig_import_helper
else:
    import _enrichment_tools
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _enrichment_tools.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _enrichment_tools.SwigPyIterator_value(self)
    def incr(self, n = 1): return _enrichment_tools.SwigPyIterator_incr(self, n)
    def decr(self, n = 1): return _enrichment_tools.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _enrichment_tools.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _enrichment_tools.SwigPyIterator_equal(self, *args)
    def copy(self): return _enrichment_tools.SwigPyIterator_copy(self)
    def next(self): return _enrichment_tools.SwigPyIterator_next(self)
    def __next__(self): return _enrichment_tools.SwigPyIterator___next__(self)
    def previous(self): return _enrichment_tools.SwigPyIterator_previous(self)
    def advance(self, *args): return _enrichment_tools.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _enrichment_tools.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _enrichment_tools.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _enrichment_tools.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _enrichment_tools.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _enrichment_tools.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _enrichment_tools.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _enrichment_tools.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class SizeVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SizeVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SizeVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _enrichment_tools.SizeVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _enrichment_tools.SizeVector___nonzero__(self)
    def __bool__(self): return _enrichment_tools.SizeVector___bool__(self)
    def __len__(self): return _enrichment_tools.SizeVector___len__(self)
    def pop(self): return _enrichment_tools.SizeVector_pop(self)
    def __getslice__(self, *args): return _enrichment_tools.SizeVector___getslice__(self, *args)
    def __setslice__(self, *args): return _enrichment_tools.SizeVector___setslice__(self, *args)
    def __delslice__(self, *args): return _enrichment_tools.SizeVector___delslice__(self, *args)
    def __delitem__(self, *args): return _enrichment_tools.SizeVector___delitem__(self, *args)
    def __getitem__(self, *args): return _enrichment_tools.SizeVector___getitem__(self, *args)
    def __setitem__(self, *args): return _enrichment_tools.SizeVector___setitem__(self, *args)
    def append(self, *args): return _enrichment_tools.SizeVector_append(self, *args)
    def empty(self): return _enrichment_tools.SizeVector_empty(self)
    def size(self): return _enrichment_tools.SizeVector_size(self)
    def clear(self): return _enrichment_tools.SizeVector_clear(self)
    def swap(self, *args): return _enrichment_tools.SizeVector_swap(self, *args)
    def get_allocator(self): return _enrichment_tools.SizeVector_get_allocator(self)
    def begin(self): return _enrichment_tools.SizeVector_begin(self)
    def end(self): return _enrichment_tools.SizeVector_end(self)
    def rbegin(self): return _enrichment_tools.SizeVector_rbegin(self)
    def rend(self): return _enrichment_tools.SizeVector_rend(self)
    def pop_back(self): return _enrichment_tools.SizeVector_pop_back(self)
    def erase(self, *args): return _enrichment_tools.SizeVector_erase(self, *args)
    def __init__(self, *args): 
        this = _enrichment_tools.new_SizeVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _enrichment_tools.SizeVector_push_back(self, *args)
    def front(self): return _enrichment_tools.SizeVector_front(self)
    def back(self): return _enrichment_tools.SizeVector_back(self)
    def assign(self, *args): return _enrichment_tools.SizeVector_assign(self, *args)
    def resize(self, *args): return _enrichment_tools.SizeVector_resize(self, *args)
    def insert(self, *args): return _enrichment_tools.SizeVector_insert(self, *args)
    def reserve(self, *args): return _enrichment_tools.SizeVector_reserve(self, *args)
    def capacity(self): return _enrichment_tools.SizeVector_capacity(self)
    __swig_destroy__ = _enrichment_tools.delete_SizeVector
    __del__ = lambda self : None;
SizeVector_swigregister = _enrichment_tools.SizeVector_swigregister
SizeVector_swigregister(SizeVector)

class StringArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringArray, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _enrichment_tools.new_StringArray(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _enrichment_tools.delete_StringArray
    __del__ = lambda self : None;
    def __getitem__(self, *args): return _enrichment_tools.StringArray___getitem__(self, *args)
    def __setitem__(self, *args): return _enrichment_tools.StringArray___setitem__(self, *args)
    def cast(self): return _enrichment_tools.StringArray_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _enrichment_tools.StringArray_frompointer
    if _newclass:frompointer = staticmethod(_enrichment_tools.StringArray_frompointer)
StringArray_swigregister = _enrichment_tools.StringArray_swigregister
StringArray_swigregister(StringArray)

def StringArray_frompointer(*args):
  return _enrichment_tools.StringArray_frompointer(*args)
StringArray_frompointer = _enrichment_tools.StringArray_frompointer

class StringVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _enrichment_tools.StringVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _enrichment_tools.StringVector___nonzero__(self)
    def __bool__(self): return _enrichment_tools.StringVector___bool__(self)
    def __len__(self): return _enrichment_tools.StringVector___len__(self)
    def pop(self): return _enrichment_tools.StringVector_pop(self)
    def __getslice__(self, *args): return _enrichment_tools.StringVector___getslice__(self, *args)
    def __setslice__(self, *args): return _enrichment_tools.StringVector___setslice__(self, *args)
    def __delslice__(self, *args): return _enrichment_tools.StringVector___delslice__(self, *args)
    def __delitem__(self, *args): return _enrichment_tools.StringVector___delitem__(self, *args)
    def __getitem__(self, *args): return _enrichment_tools.StringVector___getitem__(self, *args)
    def __setitem__(self, *args): return _enrichment_tools.StringVector___setitem__(self, *args)
    def append(self, *args): return _enrichment_tools.StringVector_append(self, *args)
    def empty(self): return _enrichment_tools.StringVector_empty(self)
    def size(self): return _enrichment_tools.StringVector_size(self)
    def clear(self): return _enrichment_tools.StringVector_clear(self)
    def swap(self, *args): return _enrichment_tools.StringVector_swap(self, *args)
    def get_allocator(self): return _enrichment_tools.StringVector_get_allocator(self)
    def begin(self): return _enrichment_tools.StringVector_begin(self)
    def end(self): return _enrichment_tools.StringVector_end(self)
    def rbegin(self): return _enrichment_tools.StringVector_rbegin(self)
    def rend(self): return _enrichment_tools.StringVector_rend(self)
    def pop_back(self): return _enrichment_tools.StringVector_pop_back(self)
    def erase(self, *args): return _enrichment_tools.StringVector_erase(self, *args)
    def __init__(self, *args): 
        this = _enrichment_tools.new_StringVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _enrichment_tools.StringVector_push_back(self, *args)
    def front(self): return _enrichment_tools.StringVector_front(self)
    def back(self): return _enrichment_tools.StringVector_back(self)
    def assign(self, *args): return _enrichment_tools.StringVector_assign(self, *args)
    def resize(self, *args): return _enrichment_tools.StringVector_resize(self, *args)
    def insert(self, *args): return _enrichment_tools.StringVector_insert(self, *args)
    def reserve(self, *args): return _enrichment_tools.StringVector_reserve(self, *args)
    def capacity(self): return _enrichment_tools.StringVector_capacity(self)
    __swig_destroy__ = _enrichment_tools.delete_StringVector
    __del__ = lambda self : None;
StringVector_swigregister = _enrichment_tools.StringVector_swigregister
StringVector_swigregister(StringVector)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _enrichment_tools.DoubleVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _enrichment_tools.DoubleVector___nonzero__(self)
    def __bool__(self): return _enrichment_tools.DoubleVector___bool__(self)
    def __len__(self): return _enrichment_tools.DoubleVector___len__(self)
    def pop(self): return _enrichment_tools.DoubleVector_pop(self)
    def __getslice__(self, *args): return _enrichment_tools.DoubleVector___getslice__(self, *args)
    def __setslice__(self, *args): return _enrichment_tools.DoubleVector___setslice__(self, *args)
    def __delslice__(self, *args): return _enrichment_tools.DoubleVector___delslice__(self, *args)
    def __delitem__(self, *args): return _enrichment_tools.DoubleVector___delitem__(self, *args)
    def __getitem__(self, *args): return _enrichment_tools.DoubleVector___getitem__(self, *args)
    def __setitem__(self, *args): return _enrichment_tools.DoubleVector___setitem__(self, *args)
    def append(self, *args): return _enrichment_tools.DoubleVector_append(self, *args)
    def empty(self): return _enrichment_tools.DoubleVector_empty(self)
    def size(self): return _enrichment_tools.DoubleVector_size(self)
    def clear(self): return _enrichment_tools.DoubleVector_clear(self)
    def swap(self, *args): return _enrichment_tools.DoubleVector_swap(self, *args)
    def get_allocator(self): return _enrichment_tools.DoubleVector_get_allocator(self)
    def begin(self): return _enrichment_tools.DoubleVector_begin(self)
    def end(self): return _enrichment_tools.DoubleVector_end(self)
    def rbegin(self): return _enrichment_tools.DoubleVector_rbegin(self)
    def rend(self): return _enrichment_tools.DoubleVector_rend(self)
    def pop_back(self): return _enrichment_tools.DoubleVector_pop_back(self)
    def erase(self, *args): return _enrichment_tools.DoubleVector_erase(self, *args)
    def __init__(self, *args): 
        this = _enrichment_tools.new_DoubleVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _enrichment_tools.DoubleVector_push_back(self, *args)
    def front(self): return _enrichment_tools.DoubleVector_front(self)
    def back(self): return _enrichment_tools.DoubleVector_back(self)
    def assign(self, *args): return _enrichment_tools.DoubleVector_assign(self, *args)
    def resize(self, *args): return _enrichment_tools.DoubleVector_resize(self, *args)
    def insert(self, *args): return _enrichment_tools.DoubleVector_insert(self, *args)
    def reserve(self, *args): return _enrichment_tools.DoubleVector_reserve(self, *args)
    def capacity(self): return _enrichment_tools.DoubleVector_capacity(self)
    __swig_destroy__ = _enrichment_tools.delete_DoubleVector
    __del__ = lambda self : None;
DoubleVector_swigregister = _enrichment_tools.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)

class BoostSet(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BoostSet, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BoostSet, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _enrichment_tools.new_BoostSet()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _enrichment_tools.delete_BoostSet
    __del__ = lambda self : None;
BoostSet_swigregister = _enrichment_tools.BoostSet_swigregister
BoostSet_swigregister(BoostSet)


def getDescendantGenes(*args):
  return _enrichment_tools.getDescendantGenes(*args)
getDescendantGenes = _enrichment_tools.getDescendantGenes

def oneSidedRawPvalue_hyper(*args):
  return _enrichment_tools.oneSidedRawPvalue_hyper(*args)
oneSidedRawPvalue_hyper = _enrichment_tools.oneSidedRawPvalue_hyper

def enrichmentSignificance(*args):
  return _enrichment_tools.enrichmentSignificance(*args)
enrichmentSignificance = _enrichment_tools.enrichmentSignificance


