# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_term_set_sim', [dirname(__file__)])
        except ImportError:
            import _term_set_sim
            return _term_set_sim
        if fp is not None:
            try:
                _mod = imp.load_module('_term_set_sim', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _term_set_sim = swig_import_helper()
    del swig_import_helper
else:
    import _term_set_sim
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _term_set_sim.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _term_set_sim.SwigPyIterator_value(self)
    def incr(self, n = 1): return _term_set_sim.SwigPyIterator_incr(self, n)
    def decr(self, n = 1): return _term_set_sim.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _term_set_sim.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _term_set_sim.SwigPyIterator_equal(self, *args)
    def copy(self): return _term_set_sim.SwigPyIterator_copy(self)
    def next(self): return _term_set_sim.SwigPyIterator_next(self)
    def __next__(self): return _term_set_sim.SwigPyIterator___next__(self)
    def previous(self): return _term_set_sim.SwigPyIterator_previous(self)
    def advance(self, *args): return _term_set_sim.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _term_set_sim.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _term_set_sim.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _term_set_sim.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _term_set_sim.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _term_set_sim.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _term_set_sim.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _term_set_sim.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class SizeVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SizeVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SizeVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _term_set_sim.SizeVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _term_set_sim.SizeVector___nonzero__(self)
    def __bool__(self): return _term_set_sim.SizeVector___bool__(self)
    def __len__(self): return _term_set_sim.SizeVector___len__(self)
    def pop(self): return _term_set_sim.SizeVector_pop(self)
    def __getslice__(self, *args): return _term_set_sim.SizeVector___getslice__(self, *args)
    def __setslice__(self, *args): return _term_set_sim.SizeVector___setslice__(self, *args)
    def __delslice__(self, *args): return _term_set_sim.SizeVector___delslice__(self, *args)
    def __delitem__(self, *args): return _term_set_sim.SizeVector___delitem__(self, *args)
    def __getitem__(self, *args): return _term_set_sim.SizeVector___getitem__(self, *args)
    def __setitem__(self, *args): return _term_set_sim.SizeVector___setitem__(self, *args)
    def append(self, *args): return _term_set_sim.SizeVector_append(self, *args)
    def empty(self): return _term_set_sim.SizeVector_empty(self)
    def size(self): return _term_set_sim.SizeVector_size(self)
    def clear(self): return _term_set_sim.SizeVector_clear(self)
    def swap(self, *args): return _term_set_sim.SizeVector_swap(self, *args)
    def get_allocator(self): return _term_set_sim.SizeVector_get_allocator(self)
    def begin(self): return _term_set_sim.SizeVector_begin(self)
    def end(self): return _term_set_sim.SizeVector_end(self)
    def rbegin(self): return _term_set_sim.SizeVector_rbegin(self)
    def rend(self): return _term_set_sim.SizeVector_rend(self)
    def pop_back(self): return _term_set_sim.SizeVector_pop_back(self)
    def erase(self, *args): return _term_set_sim.SizeVector_erase(self, *args)
    def __init__(self, *args): 
        this = _term_set_sim.new_SizeVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _term_set_sim.SizeVector_push_back(self, *args)
    def front(self): return _term_set_sim.SizeVector_front(self)
    def back(self): return _term_set_sim.SizeVector_back(self)
    def assign(self, *args): return _term_set_sim.SizeVector_assign(self, *args)
    def resize(self, *args): return _term_set_sim.SizeVector_resize(self, *args)
    def insert(self, *args): return _term_set_sim.SizeVector_insert(self, *args)
    def reserve(self, *args): return _term_set_sim.SizeVector_reserve(self, *args)
    def capacity(self): return _term_set_sim.SizeVector_capacity(self)
    __swig_destroy__ = _term_set_sim.delete_SizeVector
    __del__ = lambda self : None;
SizeVector_swigregister = _term_set_sim.SizeVector_swigregister
SizeVector_swigregister(SizeVector)

class StringArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringArray, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _term_set_sim.new_StringArray(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _term_set_sim.delete_StringArray
    __del__ = lambda self : None;
    def __getitem__(self, *args): return _term_set_sim.StringArray___getitem__(self, *args)
    def __setitem__(self, *args): return _term_set_sim.StringArray___setitem__(self, *args)
    def cast(self): return _term_set_sim.StringArray_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _term_set_sim.StringArray_frompointer
    if _newclass:frompointer = staticmethod(_term_set_sim.StringArray_frompointer)
StringArray_swigregister = _term_set_sim.StringArray_swigregister
StringArray_swigregister(StringArray)

def StringArray_frompointer(*args):
  return _term_set_sim.StringArray_frompointer(*args)
StringArray_frompointer = _term_set_sim.StringArray_frompointer

class StringVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _term_set_sim.StringVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _term_set_sim.StringVector___nonzero__(self)
    def __bool__(self): return _term_set_sim.StringVector___bool__(self)
    def __len__(self): return _term_set_sim.StringVector___len__(self)
    def pop(self): return _term_set_sim.StringVector_pop(self)
    def __getslice__(self, *args): return _term_set_sim.StringVector___getslice__(self, *args)
    def __setslice__(self, *args): return _term_set_sim.StringVector___setslice__(self, *args)
    def __delslice__(self, *args): return _term_set_sim.StringVector___delslice__(self, *args)
    def __delitem__(self, *args): return _term_set_sim.StringVector___delitem__(self, *args)
    def __getitem__(self, *args): return _term_set_sim.StringVector___getitem__(self, *args)
    def __setitem__(self, *args): return _term_set_sim.StringVector___setitem__(self, *args)
    def append(self, *args): return _term_set_sim.StringVector_append(self, *args)
    def empty(self): return _term_set_sim.StringVector_empty(self)
    def size(self): return _term_set_sim.StringVector_size(self)
    def clear(self): return _term_set_sim.StringVector_clear(self)
    def swap(self, *args): return _term_set_sim.StringVector_swap(self, *args)
    def get_allocator(self): return _term_set_sim.StringVector_get_allocator(self)
    def begin(self): return _term_set_sim.StringVector_begin(self)
    def end(self): return _term_set_sim.StringVector_end(self)
    def rbegin(self): return _term_set_sim.StringVector_rbegin(self)
    def rend(self): return _term_set_sim.StringVector_rend(self)
    def pop_back(self): return _term_set_sim.StringVector_pop_back(self)
    def erase(self, *args): return _term_set_sim.StringVector_erase(self, *args)
    def __init__(self, *args): 
        this = _term_set_sim.new_StringVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _term_set_sim.StringVector_push_back(self, *args)
    def front(self): return _term_set_sim.StringVector_front(self)
    def back(self): return _term_set_sim.StringVector_back(self)
    def assign(self, *args): return _term_set_sim.StringVector_assign(self, *args)
    def resize(self, *args): return _term_set_sim.StringVector_resize(self, *args)
    def insert(self, *args): return _term_set_sim.StringVector_insert(self, *args)
    def reserve(self, *args): return _term_set_sim.StringVector_reserve(self, *args)
    def capacity(self): return _term_set_sim.StringVector_capacity(self)
    __swig_destroy__ = _term_set_sim.delete_StringVector
    __del__ = lambda self : None;
StringVector_swigregister = _term_set_sim.StringVector_swigregister
StringVector_swigregister(StringVector)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _term_set_sim.DoubleVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _term_set_sim.DoubleVector___nonzero__(self)
    def __bool__(self): return _term_set_sim.DoubleVector___bool__(self)
    def __len__(self): return _term_set_sim.DoubleVector___len__(self)
    def pop(self): return _term_set_sim.DoubleVector_pop(self)
    def __getslice__(self, *args): return _term_set_sim.DoubleVector___getslice__(self, *args)
    def __setslice__(self, *args): return _term_set_sim.DoubleVector___setslice__(self, *args)
    def __delslice__(self, *args): return _term_set_sim.DoubleVector___delslice__(self, *args)
    def __delitem__(self, *args): return _term_set_sim.DoubleVector___delitem__(self, *args)
    def __getitem__(self, *args): return _term_set_sim.DoubleVector___getitem__(self, *args)
    def __setitem__(self, *args): return _term_set_sim.DoubleVector___setitem__(self, *args)
    def append(self, *args): return _term_set_sim.DoubleVector_append(self, *args)
    def empty(self): return _term_set_sim.DoubleVector_empty(self)
    def size(self): return _term_set_sim.DoubleVector_size(self)
    def clear(self): return _term_set_sim.DoubleVector_clear(self)
    def swap(self, *args): return _term_set_sim.DoubleVector_swap(self, *args)
    def get_allocator(self): return _term_set_sim.DoubleVector_get_allocator(self)
    def begin(self): return _term_set_sim.DoubleVector_begin(self)
    def end(self): return _term_set_sim.DoubleVector_end(self)
    def rbegin(self): return _term_set_sim.DoubleVector_rbegin(self)
    def rend(self): return _term_set_sim.DoubleVector_rend(self)
    def pop_back(self): return _term_set_sim.DoubleVector_pop_back(self)
    def erase(self, *args): return _term_set_sim.DoubleVector_erase(self, *args)
    def __init__(self, *args): 
        this = _term_set_sim.new_DoubleVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _term_set_sim.DoubleVector_push_back(self, *args)
    def front(self): return _term_set_sim.DoubleVector_front(self)
    def back(self): return _term_set_sim.DoubleVector_back(self)
    def assign(self, *args): return _term_set_sim.DoubleVector_assign(self, *args)
    def resize(self, *args): return _term_set_sim.DoubleVector_resize(self, *args)
    def insert(self, *args): return _term_set_sim.DoubleVector_insert(self, *args)
    def reserve(self, *args): return _term_set_sim.DoubleVector_reserve(self, *args)
    def capacity(self): return _term_set_sim.DoubleVector_capacity(self)
    __swig_destroy__ = _term_set_sim.delete_DoubleVector
    __del__ = lambda self : None;
DoubleVector_swigregister = _term_set_sim.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)

class BoostSet(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BoostSet, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BoostSet, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _term_set_sim.new_BoostSet()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _term_set_sim.delete_BoostSet
    __del__ = lambda self : None;
BoostSet_swigregister = _term_set_sim.BoostSet_swigregister
BoostSet_swigregister(BoostSet)

class TermSimilarityInterface(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TermSimilarityInterface, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TermSimilarityInterface, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    def calculateTermSimilarity(self, *args): return _term_set_sim.TermSimilarityInterface_calculateTermSimilarity(self, *args)
    def calculateNormalizedTermSimilarity(self, *args): return _term_set_sim.TermSimilarityInterface_calculateNormalizedTermSimilarity(self, *args)
    __swig_destroy__ = _term_set_sim.delete_TermSimilarityInterface
    __del__ = lambda self : None;
TermSimilarityInterface_swigregister = _term_set_sim.TermSimilarityInterface_swigregister
TermSimilarityInterface_swigregister(TermSimilarityInterface)

class TermSetSimilarityInterface(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TermSetSimilarityInterface, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TermSetSimilarityInterface, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    def calculateSimilarity(self, *args): return _term_set_sim.TermSetSimilarityInterface_calculateSimilarity(self, *args)
    __swig_destroy__ = _term_set_sim.delete_TermSetSimilarityInterface
    __del__ = lambda self : None;
TermSetSimilarityInterface_swigregister = _term_set_sim.TermSetSimilarityInterface_swigregister
TermSetSimilarityInterface_swigregister(TermSetSimilarityInterface)

class AllPairsAverageSetSimilarity(TermSetSimilarityInterface):
    __swig_setmethods__ = {}
    for _s in [TermSetSimilarityInterface]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, AllPairsAverageSetSimilarity, name, value)
    __swig_getmethods__ = {}
    for _s in [TermSetSimilarityInterface]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, AllPairsAverageSetSimilarity, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _term_set_sim.new_AllPairsAverageSetSimilarity(*args)
        try: self.this.append(this)
        except: self.this = this
    def calculateSimilarity(self, *args): return _term_set_sim.AllPairsAverageSetSimilarity_calculateSimilarity(self, *args)
    __swig_destroy__ = _term_set_sim.delete_AllPairsAverageSetSimilarity
    __del__ = lambda self : None;
AllPairsAverageSetSimilarity_swigregister = _term_set_sim.AllPairsAverageSetSimilarity_swigregister
AllPairsAverageSetSimilarity_swigregister(AllPairsAverageSetSimilarity)

class AllPairsMaxSetSimilarity(TermSetSimilarityInterface):
    __swig_setmethods__ = {}
    for _s in [TermSetSimilarityInterface]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, AllPairsMaxSetSimilarity, name, value)
    __swig_getmethods__ = {}
    for _s in [TermSetSimilarityInterface]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, AllPairsMaxSetSimilarity, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _term_set_sim.new_AllPairsMaxSetSimilarity(*args)
        try: self.this.append(this)
        except: self.this = this
    def calculateSimilarity(self, *args): return _term_set_sim.AllPairsMaxSetSimilarity_calculateSimilarity(self, *args)
    __swig_destroy__ = _term_set_sim.delete_AllPairsMaxSetSimilarity
    __del__ = lambda self : None;
AllPairsMaxSetSimilarity_swigregister = _term_set_sim.AllPairsMaxSetSimilarity_swigregister
AllPairsMaxSetSimilarity_swigregister(AllPairsMaxSetSimilarity)

class BestMatchAverageSetSimilarity(TermSetSimilarityInterface):
    __swig_setmethods__ = {}
    for _s in [TermSetSimilarityInterface]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, BestMatchAverageSetSimilarity, name, value)
    __swig_getmethods__ = {}
    for _s in [TermSetSimilarityInterface]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, BestMatchAverageSetSimilarity, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _term_set_sim.new_BestMatchAverageSetSimilarity(*args)
        try: self.this.append(this)
        except: self.this = this
    def calculateSimilarity(self, *args): return _term_set_sim.BestMatchAverageSetSimilarity_calculateSimilarity(self, *args)
    __swig_destroy__ = _term_set_sim.delete_BestMatchAverageSetSimilarity
    __del__ = lambda self : None;
BestMatchAverageSetSimilarity_swigregister = _term_set_sim.BestMatchAverageSetSimilarity_swigregister
BestMatchAverageSetSimilarity_swigregister(BestMatchAverageSetSimilarity)

class GentlemanUISimilarity(TermSetSimilarityInterface):
    __swig_setmethods__ = {}
    for _s in [TermSetSimilarityInterface]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, GentlemanUISimilarity, name, value)
    __swig_getmethods__ = {}
    for _s in [TermSetSimilarityInterface]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, GentlemanUISimilarity, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    def calculateSimilarity(self, *args): return _term_set_sim.GentlemanUISimilarity_calculateSimilarity(self, *args)
    __swig_destroy__ = _term_set_sim.delete_GentlemanUISimilarity
    __del__ = lambda self : None;
GentlemanUISimilarity_swigregister = _term_set_sim.GentlemanUISimilarity_swigregister
GentlemanUISimilarity_swigregister(GentlemanUISimilarity)

class JaccardSetSimilarity(TermSetSimilarityInterface):
    __swig_setmethods__ = {}
    for _s in [TermSetSimilarityInterface]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, JaccardSetSimilarity, name, value)
    __swig_getmethods__ = {}
    for _s in [TermSetSimilarityInterface]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, JaccardSetSimilarity, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _term_set_sim.new_JaccardSetSimilarity()
        try: self.this.append(this)
        except: self.this = this
    def calculateSimilarity(self, *args): return _term_set_sim.JaccardSetSimilarity_calculateSimilarity(self, *args)
    __swig_destroy__ = _term_set_sim.delete_JaccardSetSimilarity
    __del__ = lambda self : None;
JaccardSetSimilarity_swigregister = _term_set_sim.JaccardSetSimilarity_swigregister
JaccardSetSimilarity_swigregister(JaccardSetSimilarity)



