# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_term_maps', [dirname(__file__)])
        except ImportError:
            import _term_maps
            return _term_maps
        if fp is not None:
            try:
                _mod = imp.load_module('_term_maps', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _term_maps = swig_import_helper()
    del swig_import_helper
else:
    import _term_maps
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _term_maps.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _term_maps.SwigPyIterator_value(self)
    def incr(self, n = 1): return _term_maps.SwigPyIterator_incr(self, n)
    def decr(self, n = 1): return _term_maps.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _term_maps.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _term_maps.SwigPyIterator_equal(self, *args)
    def copy(self): return _term_maps.SwigPyIterator_copy(self)
    def next(self): return _term_maps.SwigPyIterator_next(self)
    def __next__(self): return _term_maps.SwigPyIterator___next__(self)
    def previous(self): return _term_maps.SwigPyIterator_previous(self)
    def advance(self, *args): return _term_maps.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _term_maps.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _term_maps.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _term_maps.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _term_maps.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _term_maps.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _term_maps.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _term_maps.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class SizeVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SizeVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SizeVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _term_maps.SizeVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _term_maps.SizeVector___nonzero__(self)
    def __bool__(self): return _term_maps.SizeVector___bool__(self)
    def __len__(self): return _term_maps.SizeVector___len__(self)
    def pop(self): return _term_maps.SizeVector_pop(self)
    def __getslice__(self, *args): return _term_maps.SizeVector___getslice__(self, *args)
    def __setslice__(self, *args): return _term_maps.SizeVector___setslice__(self, *args)
    def __delslice__(self, *args): return _term_maps.SizeVector___delslice__(self, *args)
    def __delitem__(self, *args): return _term_maps.SizeVector___delitem__(self, *args)
    def __getitem__(self, *args): return _term_maps.SizeVector___getitem__(self, *args)
    def __setitem__(self, *args): return _term_maps.SizeVector___setitem__(self, *args)
    def append(self, *args): return _term_maps.SizeVector_append(self, *args)
    def empty(self): return _term_maps.SizeVector_empty(self)
    def size(self): return _term_maps.SizeVector_size(self)
    def clear(self): return _term_maps.SizeVector_clear(self)
    def swap(self, *args): return _term_maps.SizeVector_swap(self, *args)
    def get_allocator(self): return _term_maps.SizeVector_get_allocator(self)
    def begin(self): return _term_maps.SizeVector_begin(self)
    def end(self): return _term_maps.SizeVector_end(self)
    def rbegin(self): return _term_maps.SizeVector_rbegin(self)
    def rend(self): return _term_maps.SizeVector_rend(self)
    def pop_back(self): return _term_maps.SizeVector_pop_back(self)
    def erase(self, *args): return _term_maps.SizeVector_erase(self, *args)
    def __init__(self, *args): 
        this = _term_maps.new_SizeVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _term_maps.SizeVector_push_back(self, *args)
    def front(self): return _term_maps.SizeVector_front(self)
    def back(self): return _term_maps.SizeVector_back(self)
    def assign(self, *args): return _term_maps.SizeVector_assign(self, *args)
    def resize(self, *args): return _term_maps.SizeVector_resize(self, *args)
    def insert(self, *args): return _term_maps.SizeVector_insert(self, *args)
    def reserve(self, *args): return _term_maps.SizeVector_reserve(self, *args)
    def capacity(self): return _term_maps.SizeVector_capacity(self)
    __swig_destroy__ = _term_maps.delete_SizeVector
    __del__ = lambda self : None;
SizeVector_swigregister = _term_maps.SizeVector_swigregister
SizeVector_swigregister(SizeVector)

class StringArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringArray, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _term_maps.new_StringArray(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _term_maps.delete_StringArray
    __del__ = lambda self : None;
    def __getitem__(self, *args): return _term_maps.StringArray___getitem__(self, *args)
    def __setitem__(self, *args): return _term_maps.StringArray___setitem__(self, *args)
    def cast(self): return _term_maps.StringArray_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _term_maps.StringArray_frompointer
    if _newclass:frompointer = staticmethod(_term_maps.StringArray_frompointer)
StringArray_swigregister = _term_maps.StringArray_swigregister
StringArray_swigregister(StringArray)

def StringArray_frompointer(*args):
  return _term_maps.StringArray_frompointer(*args)
StringArray_frompointer = _term_maps.StringArray_frompointer

class StringVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _term_maps.StringVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _term_maps.StringVector___nonzero__(self)
    def __bool__(self): return _term_maps.StringVector___bool__(self)
    def __len__(self): return _term_maps.StringVector___len__(self)
    def pop(self): return _term_maps.StringVector_pop(self)
    def __getslice__(self, *args): return _term_maps.StringVector___getslice__(self, *args)
    def __setslice__(self, *args): return _term_maps.StringVector___setslice__(self, *args)
    def __delslice__(self, *args): return _term_maps.StringVector___delslice__(self, *args)
    def __delitem__(self, *args): return _term_maps.StringVector___delitem__(self, *args)
    def __getitem__(self, *args): return _term_maps.StringVector___getitem__(self, *args)
    def __setitem__(self, *args): return _term_maps.StringVector___setitem__(self, *args)
    def append(self, *args): return _term_maps.StringVector_append(self, *args)
    def empty(self): return _term_maps.StringVector_empty(self)
    def size(self): return _term_maps.StringVector_size(self)
    def clear(self): return _term_maps.StringVector_clear(self)
    def swap(self, *args): return _term_maps.StringVector_swap(self, *args)
    def get_allocator(self): return _term_maps.StringVector_get_allocator(self)
    def begin(self): return _term_maps.StringVector_begin(self)
    def end(self): return _term_maps.StringVector_end(self)
    def rbegin(self): return _term_maps.StringVector_rbegin(self)
    def rend(self): return _term_maps.StringVector_rend(self)
    def pop_back(self): return _term_maps.StringVector_pop_back(self)
    def erase(self, *args): return _term_maps.StringVector_erase(self, *args)
    def __init__(self, *args): 
        this = _term_maps.new_StringVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _term_maps.StringVector_push_back(self, *args)
    def front(self): return _term_maps.StringVector_front(self)
    def back(self): return _term_maps.StringVector_back(self)
    def assign(self, *args): return _term_maps.StringVector_assign(self, *args)
    def resize(self, *args): return _term_maps.StringVector_resize(self, *args)
    def insert(self, *args): return _term_maps.StringVector_insert(self, *args)
    def reserve(self, *args): return _term_maps.StringVector_reserve(self, *args)
    def capacity(self): return _term_maps.StringVector_capacity(self)
    __swig_destroy__ = _term_maps.delete_StringVector
    __del__ = lambda self : None;
StringVector_swigregister = _term_maps.StringVector_swigregister
StringVector_swigregister(StringVector)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _term_maps.DoubleVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _term_maps.DoubleVector___nonzero__(self)
    def __bool__(self): return _term_maps.DoubleVector___bool__(self)
    def __len__(self): return _term_maps.DoubleVector___len__(self)
    def pop(self): return _term_maps.DoubleVector_pop(self)
    def __getslice__(self, *args): return _term_maps.DoubleVector___getslice__(self, *args)
    def __setslice__(self, *args): return _term_maps.DoubleVector___setslice__(self, *args)
    def __delslice__(self, *args): return _term_maps.DoubleVector___delslice__(self, *args)
    def __delitem__(self, *args): return _term_maps.DoubleVector___delitem__(self, *args)
    def __getitem__(self, *args): return _term_maps.DoubleVector___getitem__(self, *args)
    def __setitem__(self, *args): return _term_maps.DoubleVector___setitem__(self, *args)
    def append(self, *args): return _term_maps.DoubleVector_append(self, *args)
    def empty(self): return _term_maps.DoubleVector_empty(self)
    def size(self): return _term_maps.DoubleVector_size(self)
    def clear(self): return _term_maps.DoubleVector_clear(self)
    def swap(self, *args): return _term_maps.DoubleVector_swap(self, *args)
    def get_allocator(self): return _term_maps.DoubleVector_get_allocator(self)
    def begin(self): return _term_maps.DoubleVector_begin(self)
    def end(self): return _term_maps.DoubleVector_end(self)
    def rbegin(self): return _term_maps.DoubleVector_rbegin(self)
    def rend(self): return _term_maps.DoubleVector_rend(self)
    def pop_back(self): return _term_maps.DoubleVector_pop_back(self)
    def erase(self, *args): return _term_maps.DoubleVector_erase(self, *args)
    def __init__(self, *args): 
        this = _term_maps.new_DoubleVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _term_maps.DoubleVector_push_back(self, *args)
    def front(self): return _term_maps.DoubleVector_front(self)
    def back(self): return _term_maps.DoubleVector_back(self)
    def assign(self, *args): return _term_maps.DoubleVector_assign(self, *args)
    def resize(self, *args): return _term_maps.DoubleVector_resize(self, *args)
    def insert(self, *args): return _term_maps.DoubleVector_insert(self, *args)
    def reserve(self, *args): return _term_maps.DoubleVector_reserve(self, *args)
    def capacity(self): return _term_maps.DoubleVector_capacity(self)
    __swig_destroy__ = _term_maps.delete_DoubleVector
    __del__ = lambda self : None;
DoubleVector_swigregister = _term_maps.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)

class BoostSet(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BoostSet, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BoostSet, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _term_maps.new_BoostSet()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _term_maps.delete_BoostSet
    __del__ = lambda self : None;
BoostSet_swigregister = _term_maps.BoostSet_swigregister
BoostSet_swigregister(BoostSet)

class TermProbabilityMap(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TermProbabilityMap, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TermProbabilityMap, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _term_maps.new_TermProbabilityMap(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _term_maps.delete_TermProbabilityMap
    __del__ = lambda self : None;
    def getValues(self): return _term_maps.TermProbabilityMap_getValues(self)
    def getKeys(self): return _term_maps.TermProbabilityMap_getKeys(self)
    def hasTerm(self, *args): return _term_maps.TermProbabilityMap_hasTerm(self, *args)
    def badIdValue(self): return _term_maps.TermProbabilityMap_badIdValue(self)
    def getValue(self, *args): return _term_maps.TermProbabilityMap_getValue(self, *args)
    def getMinBP(self): return _term_maps.TermProbabilityMap_getMinBP(self)
    def getMinMF(self): return _term_maps.TermProbabilityMap_getMinMF(self)
    def getMinCC(self): return _term_maps.TermProbabilityMap_getMinCC(self)
TermProbabilityMap_swigregister = _term_maps.TermProbabilityMap_swigregister
TermProbabilityMap_swigregister(TermProbabilityMap)

class TermInformationContentMap(TermProbabilityMap):
    __swig_setmethods__ = {}
    for _s in [TermProbabilityMap]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, TermInformationContentMap, name, value)
    __swig_getmethods__ = {}
    for _s in [TermProbabilityMap]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, TermInformationContentMap, name)
    __repr__ = _swig_repr
    def badIdValue(self): return _term_maps.TermInformationContentMap_badIdValue(self)
    def __init__(self, *args): 
        this = _term_maps.new_TermInformationContentMap(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _term_maps.delete_TermInformationContentMap
    __del__ = lambda self : None;
TermInformationContentMap_swigregister = _term_maps.TermInformationContentMap_swigregister
TermInformationContentMap_swigregister(TermInformationContentMap)

class TermDepthMap(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TermDepthMap, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TermDepthMap, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _term_maps.new_TermDepthMap(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _term_maps.delete_TermDepthMap
    __del__ = lambda self : None;
    def getValues(self): return _term_maps.TermDepthMap_getValues(self)
    def getKeys(self): return _term_maps.TermDepthMap_getKeys(self)
    def hasTerm(self, *args): return _term_maps.TermDepthMap_hasTerm(self, *args)
    def getValue(self, *args): return _term_maps.TermDepthMap_getValue(self, *args)
TermDepthMap_swigregister = _term_maps.TermDepthMap_swigregister
TermDepthMap_swigregister(TermDepthMap)



